#!/bin/sh
TRegGA_DIR=$(pwd)
source ${TRegGA_DIR}/TRegGA.source
EMAIL="youremail@indiana.edu"
WALLTIME=24
VMEM=500
PPN=30
CHECKONLY=no
NUMPROC=30
# CULTIVAR='\"Zhengshan97\"'
# SYNONYM="ZHENGSHAN97"
TARGET=OsjSWEET13
REFERENCE=OsjCHR12
FROM=17292001
TO=17315000

##-----------------------------------------
## No need to change below
##-----------------------------------------

len=`awk 'END { print NR }' TRegGA.sample`
for ((k=1; k<=$len; k++))
do
head -$k TRegGA.sample | tail -1 > rec
CULTIVAR=`cut -d "|" -f1 rec`
SYNONYM=`cut -d "|" -f2 rec`

echo "
#!/bin/bash
#PBS -m abe
#PBS -l nodes=1:ppn=${PPN},vmem=${VMEM}gb,walltime=${WALLTIME}:00:00
#PBS -M ${EMAIL}
#PBS -N TRegGA_${SYNONYM}-on-${TARGET}
#PBS -j oe
" > runTRegGA_${SYNONYM}-on-${TARGET}

cat ${TRegGA_DIR}/xloadmodules >> runTRegGA_${SYNONYM}-on-${TARGET}

echo "
TRegGA_DIR=${TRegGA_DIR}
source ${TRegGA_DIR}/TRegGA.source
source ${SRCDIR}/PAGIT/PAGIT/sourceme.pagit
cd ${TRegGA_DIR}

# For the read prep and no more.
# make CHECKONLY=${CHECKONLY} NUMPROC=${NUMPROC} CULTIVAR='\\\"${CULTIVAR}\\\"' SYNONYM=${SYNONYM} -f Makefile_TRegGA-orig ${TRegGA_DIR}/reads/${SYNONYM}/${SYNONYM}_1.fa >& err_${SYNONYM}-reads

# For the read prep and denovo assembly and no more.
# make CHECKONLY=${CHECKONLY} NUMPROC=${NUMPROC} CULTIVAR='\\\"${CULTIVAR}\\\"' SYNONYM=${SYNONYM} -f Makefile_TRegGA-orig ${TRegGA_DIR}/assembly/denovo/${SYNONYM}/${SYNONYM}-GF/${SYNONYM}-GF.gapfilled.final.fa >& err_${SYNONYM}-denovo

# For the target prep only
# make CHECKONLY=${CHECKONLY} NUMPROC=${NUMPROC} CULTIVAR='\\\"${CULTIVAR}\\\"' SYNONYM=${SYNONYM} TARGET=${TARGET} REFERENCE=${REFERENCE} FROM=${FROM} TO=${TO} -f Makefile_TRegGA-orig ${TRegGA_DIR}/targets/${TARGET}.embl >& err_${SYNONYM}-TargetPrep-${TARGET}

# For the entire workflow
make CHECKONLY=${CHECKONLY} NUMPROC=${NUMPROC} CULTIVAR='\\\"${CULTIVAR}\\\"' SYNONYM=${SYNONYM} TARGET=${TARGET} REFERENCE=${REFERENCE} FROM=${FROM} TO=${TO} -f Makefile_TRegGA-orig >& err_${SYNONYM}-on-${TARGET}

##---------------------------
# Traverse to ${TRegGA_DIR}/assembly/rfguided/${SYNONYM}-on-${TARGET}/EVALUATION for the assembly results.
# The assembly results can be visually evaluated against the target using the Artemis Comparson Tool (ACT):
# ${SRCDIR}/PAGIT/PAGIT/bin/act ${TARGET}.embl blastn.out ${SYNONYM}-${TARGET}.embl
# The gene structure predictions of the assembly by GenomeThreader can be found in the file gth.OsjPRT-on-${SYNONYM}-${TARGET}.

##---------------------------
## To clean up files after the job is done
# cd ${TRegGA_DIR}/reads/${SYNONYM}
# make -f Makefile_GPR_${SYNONYM} cleanup
# cd ${TRegGA_DIR}/assembly/denovo/${SYNONYM}
# make -f Makefile_denovo_${SYNONYM} cleanup
# cd ${TRegGA_DIR}/assembly/rfguided/${SYNONYM}-on-${TARGET}
# make -f Makefile_RGA_${SYNONYM}-on-${TARGET} cleanup

##-----------------------------
## To clean up files for all jobs under ${TRegGA_DIR}
# cd ${TRegGA_DIR}
# find . -path "*ALG/tmp" -type d | xargs -I {} \rm -r {}
# find . -path "*GF/alignoutput" -type d | xargs -I {} \rm -r {}
# find . -path "*GF/reads" -type d | xargs -I {} \rm -r {}

" >> runTRegGA_${SYNONYM}-on-${TARGET}
done

