#!/bin/tcsh

set repository = /home/huangcy/MYWORK/TRegGA
#set repository = /N/dc2/projects/brendelgroup/TRegGA/prj
#set repository = /N/dc2/scratch/vbrendel/TRegGA
set mythome    = `pwd`


foreach directory ( assembly/denovo assembly/rfguided reads reference targets )
  cd $directory
  foreach file ($repository/$directory/*)
    set lfile = `basename $file`
    if ( ! -e $lfile ) then
       ln -s $file
    endif
  end
  cd $mythome

end
