#!/bin/bash
#PBS -m abe
#PBS -l nodes=1:ppn=30,vmem=300gb,walltime=24:00:00
#PBS -M huangcy@indiana.edu
#PBS -N TRegGA_NIPPONBARE-denovo
#PBS -j oe

module add gcc
module add bowtie/1.1.1
module add bowtie2/2.2.3
module add bwa/0.7.6a
module add java/1.8.0_40
module add python
module add R
module add ngsutils
module add samtools
module add soapdenovo2


TRegGA_DIR=/N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1
source /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/TRegGA.source
source /N/dc2/projects/brendelgroup/TRegGA/src/PAGIT/PAGIT/sourceme.pagit
cd /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1

# For the read prep and no more.
# make -I./ -I../ -I../../ -I../../../ CHECKONLY=no NUMPROC=30 CULTIVAR=\"Nipponbare\" SYNONYM=NIPPONBARE -f Makefile_TRegGA-orig /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/reads/NIPPONBARE/NIPPONBARE_1.fa >& err_NIPPONBARE-reads

# For the read prep and denovo assembly and no more.
make -I./ -I../ -I../../ -I../../../ CHECKONLY=no NUMPROC=30 CULTIVAR=\"Nipponbare\" SYNONYM=NIPPONBARE -f Makefile_TRegGA-orig /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/assembly/denovo/NIPPONBARE/NIPPONBARE-GF/NIPPONBARE-GF.gapfilled.final.fa >& err_NIPPONBARE-denovo

# For the target prep only
# make -I./ -I../ -I../../ -I../../../ CHECKONLY=no NUMPROC=30 CULTIVAR=\"Nipponbare\" SYNONYM=NIPPONBARE TARGET=OsjSWEET13 REFERENCE=OsjCHR12 FROM=17292001 TO=17315000 -f Makefile_TRegGA-orig /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/targets/OsjSWEET13.embl >& err_NIPPONBARE-TargetPrep-OsjSWEET13

# For the entire workflow
# make -I./ -I../ -I../../ -I../../../ CHECKONLY=no NUMPROC=30 CULTIVAR=\"Nipponbare\" SYNONYM=NIPPONBARE TARGET=OsjSWEET13 REFERENCE=OsjCHR12 FROM=17292001 TO=17315000 -f Makefile_TRegGA-orig >& err_NIPPONBARE-on-OsjSWEET13


##---------------------------
# Traverse to /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/assembly/rfguided/NIPPONBARE-on-OsjSWEET13/EVALUATION for the assembly results.
# The assembly results can be visually evaluated against the target using the Artemis Comparson Tool (ACT):
# /N/dc2/projects/brendelgroup/TRegGA/src/PAGIT/PAGIT/bin/act OsjSWEET13.embl blastn.out NIPPONBARE-OsjSWEET13.embl
# The gene structure predictions of the assembly by GenomeThreader can be found in the file gth.OsjPRT-on-NIPPONBARE-OsjSWEET13.

##---------------------------
## To submit the job directly
# qsub qsub_TRegGA_NIPPONBARE-on-OsjSWEET13
## To submit the job that depends on the finish of another job with Job_Id 123456.m1.mason
# qsub -W depend=afterok:123456.m1.mason qsub_TRegGA_NIPPONBARE-on-OsjSWEET13

##----------------------------
## To clean up files after the job is done
# cd /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/reads/NIPPONBARE
# make -I ./ -I ../ -I ../../ -I ../../../ -f Makefile_GPR_NIPPONBARE cleanup
# cd /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/assembly/denovo/NIPPONBARE
# make -I ./ -I ../ -I ../../ -I ../../../ -f Makefile_denovo_NIPPONBARE cleanup
# cd /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1/assembly/rfguided/NIPPONBARE-on-OsjSWEET13
# make -I ./ -I ../ -I ../../ -I ../../../ -f Makefile_RGA_NIPPONBARE-on-OsjSWEET13 cleanup

##-----------------------------
## To clean up files for all jobs under /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1
# cd /N/dc2/projects/brendelgroup/TRegGA/TRegGA_v1
# find . -path *ALG/tmp -type d | xargs -I {} \rm -r {}
# find . -path *GF/alignoutput -type d | xargs -I {} \rm -r {}
# find . -path *GF/reads -type d | xargs -I {} \rm -r {}

