#!/usr/bin/env bash
set -exo pipefail
source ../TRegGA.source

for chr in {1..12}
do
    entret -sequence ${TRegGA_DIR}/reference/rice_japonica/Oryza_sativa.IRGSP-1.0.26.embl:$chr -outfile OsjCHR$chr.embl
    entret -sequence ${TRegGA_DIR}/reference/rice_indica/Oryza_indica.ASM465v1.26.embl:$chr -outfile OsiCHR$chr.embl
done

shasum -c checksums.sha
